dist: trusty   # Xenial build environment won't allow installation of Java 8
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    - secure: "mk/qZsqM+PGWTmBcFoBYjzGxjLFeTaj5dTuNBuBi71s9ZecaD+rO5yQsD/pCl0ylrJ3nru0mxEA0TZHPGJFmpZi2O4eejvckjCrNZzNxqPJ7wuFxltbWWB71SpD2UPGQcCTVrBG0KPK1cfUe3AduaqvX1rJbxPdgqbjJS0Rk2KWXBzdcDpMTIS0vcW6J2P783WpC1Tsc/sXZXjGtjGHGzKbpR7nzaa1Y2yBZIqhT1ZRHlW85vOBmQXgpU7p1ZUqMsWNRNsLthLkaMdjnxvvoaWjv/WwRlk717xkJbJ8PzK/oqGAZfRGDNLkpXM7O19bvWzwT1UlEnhwCTiMpJG2O5mmfULrFB76GCtkxQ4J9N5waiCdplDlZ+b1i+Q8UtJDal1Ei6hYlLxZT0/kLveT+sGbL3otIdsWJv8pXkSgJgqr34SLrLRIS5B71iWnTyKVKsesmJvkeCu8ITSmOqloLwsmKDTi/NTRJe+tF9XXH5wds8TL/EAkZk8Q+kdU3j7oFz7XJV/v2juow3RhgZYjwNGav2seXyme+P2ltwRXsvi7u+owPR3YDnEr48LOJX1S8rDY9b5GHCVdul30gfydGFlFNW3nSmiIwgrOmWRUaNaTaTAIPUOHVeWz35BkGX1ZUUzdeYUdP+wJrXRaF7KA9pAAOIUEry31BHE8qBW7/fns="
    - secure: "wIWzjlmYhwUvUkOF3YfipO/wCBRGjj7eMx0I6+r5DgdR70FPs6s/ZipFxxFmj5KpKKmmJTOTObbBZEDk4bqJ7is52s+KE488kE0AtAFk4vEwSV4b1qz6FcrbJ5j6akPMPAA3wJXkMJw51HVf9//EesQQJMZrZDt3lzffHXOUdfeqK99o6s52ieR7ltIXJ5BZ3ndmg3IW4VavfcdB1Yxc1Q8WyBa//6WD+Xuifj4JDmtEvuDJ5ALR/4lStTApjFXItAEFjb5JUCZ71gOfGoVAnCNHajBf3vVSsYZzDJDt01Oa6glUJziPyPeOaGisOsd5KO+eGLlbgJ72lV0pza4ZRKxeiwc1lUIGFTPW/kCRiSw61fMTVwXnteMmCr4WHX61KSp+vleXhv5Z4exFnA0fY9ODQxblp/EZmo+a5ywDDfbx7sZUmt9Vd0HNu+PmyNVW7tDknmowkqrX9caWCYslkH11f2sbBIRdVqkifzyFsRmYBUiGbh4n1psLCUoWL4zKf3WQ5zL5KO0FneuV+wYrlBSaWFqpHcKTHf/3Yz/vQelsI+WwBkICrkmmKLbNHKUErEMU/KIL0Ym26YSWFB0mR8ihRnPTbEjgUVyOu1IiUxzkaDIWkrgXps9u8NVG+91k6Q86+0uXjRW5V5turG1h2LSHKNXExrqIFb4XyvOy4W0="

language: ruby
rvm:
  - 2.2.0
jdk:
- oraclejdk8

before_install:
    - sudo apt-get update
    - sudo apt-get install -y curl libcurl4-openssl-dev
    
install: bundle install --jobs=3 --retry=3

addons:
  apt:
    packages:
      - oracle-java8-installer
      
script: bash cibuild.sh
after_script: travis_retry bundle exec s3_website push

cache: bundler

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master # test AND deploy the master branch

sudo: false # route the build to the container-based infrastructure for a faster build

notifications:
  email:
    - iluwatar@gmail.com
